import './style.css'

const weddingDate = new Date('2027-10-02T00:00:00')
const calendarEvent = { title:'Margo & Glenn — Onze trouwdag', location:'Hottentot Hoeve, Cassenbroek 1, 2820 Bonheiden', description:'Trouwdag van Margo & Glenn.', startDate:'20271002', endDate:'20271003', startDateTime:'2027-10-02T00:00:00', endDateTime:'2027-10-03T00:00:00' }

function createCalendarFile(){const event=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Margo & Glenn//Wedding//NL','CALSCALE:GREGORIAN','METHOD:PUBLISH','BEGIN:VEVENT','UID:margo-glenn-2027-10-02@wedding',`DTSTAMP:${formatICSDate(new Date())}`,`DTSTART;VALUE=DATE:${calendarEvent.startDate}`,`DTEND;VALUE=DATE:${calendarEvent.endDate}`,`SUMMARY:${escapeICS(calendarEvent.title)}`,`LOCATION:${escapeICS(calendarEvent.location)}`,`DESCRIPTION:${escapeICS(calendarEvent.description)}`,'END:VEVENT','END:VCALENDAR'].join('\r\n');const blob=new Blob([event],{type:'text/calendar;charset=utf-8'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download='Margo-en-Glenn-02-10-2027.ics';document.body.appendChild(link);link.click();link.remove();URL.revokeObjectURL(url)}
function formatICSDate(date){const y=date.getUTCFullYear(),m=String(date.getUTCMonth()+1).padStart(2,'0'),d=String(date.getUTCDate()).padStart(2,'0'),h=String(date.getUTCHours()).padStart(2,'0'),mi=String(date.getUTCMinutes()).padStart(2,'0'),s=String(date.getUTCSeconds()).padStart(2,'0');return `${y}${m}${d}T${h}${mi}${s}Z`}
function escapeICS(value){return String(value).replace(/\\/g,'\\\\').replace(/\r?\n/g,'\\n').replace(/;/g,'\\;').replace(/,/g,'\\,')}
function formatCountdown(){const difference=weddingDate-new Date();if(difference<=0)return 'Vandaag is onze dag ♡';const days=Math.floor(difference/86400000),hours=Math.floor(difference/3600000%24),minutes=Math.floor(difference/60000%60);return `${days} dagen · ${hours} uur · ${minutes} minuten`}
function openGoogleCalendar(){const url='https://calendar.google.com/calendar/render'+'?action=TEMPLATE'+`&text=${encodeURIComponent(calendarEvent.title)}`+`&dates=${calendarEvent.startDate}/${calendarEvent.endDate}`+`&location=${encodeURIComponent(calendarEvent.location)}`+`&details=${encodeURIComponent(calendarEvent.description)}`;window.open(url,'_blank')}
function openOutlookCalendar(){const url='https://outlook.live.com/calendar/0/deeplink/compose'+`?subject=${encodeURIComponent(calendarEvent.title)}`+`&startdt=${encodeURIComponent(calendarEvent.startDateTime)}`+`&enddt=${encodeURIComponent(calendarEvent.endDateTime)}`+`&location=${encodeURIComponent(calendarEvent.location)}`+`&body=${encodeURIComponent(calendarEvent.description)}`;window.open(url,'_blank')}

document.querySelector('#app').innerHTML=`
<main class="site">
<section class="hero"><div class="hero-decoration hero-decoration-left"></div><div class="hero-decoration hero-decoration-right"></div><div class="hero-content"><img class="wedding-logo" src="/logo.png" alt="Margo & Glenn — 2 oktober 2027"/><div class="hero-divider"><span></span><span class="heart">♡</span><span></span></div><p class="eyebrow">Onze trouwdag</p><h1>Laat ons weten<br/><em>of je er kan bij zijn</em></h1><p class="intro">Op 2 oktober 2027 willen we samen met jullie onze liefde vieren en het begin van een nieuw hoofdstuk in ons leven als man en vrouw.</p><div class="hero-actions"><a href="#rsvp" class="button button-primary">RSVP</a><button id="calendarButton" class="button button-secondary" type="button">Voeg toe aan kalender</button></div></div></section>
<section id="details" class="section details-section"><div class="section-heading"><p class="eyebrow">02 · 10 · 2027</p><h2>Onze dag</h2><div class="small-line"></div><div class="adults-only"><strong>Adults only</strong><p>Een avond zonder zorgen voor iedereen.<br/>Daarom vieren we onze dag graag samen zonder kinderen.</p></div></div><div class="details-grid"><article class="detail-card"><div class="detail-icon">♡</div><h3>Wanneer</h3><p>Zaterdag<br/><strong>2 oktober 2027</strong></p></article><article class="detail-card"><div class="detail-icon">⌖</div><h3>Waar</h3><p><strong>Hottentot Hoeve</strong><br/>Cassenbroek 1<br/>2820 Bonheiden</p><a class="text-link" href="https://www.google.com/maps/search/?api=1&query=Hottentot+Hoeve+Bonheiden" target="_blank" rel="noopener noreferrer">Bekijk de locatie →</a></article></div></section>
<section class="countdown-section"><div class="countdown-inner"><p class="eyebrow">En tot dan...</p><h2>We tellen samen af</h2><div id="countdown" class="countdown">${formatCountdown()}</div><div class="hero-divider"><span></span><span class="heart">♡</span><span></span></div></div></section>
<section class="section practical-section"><div class="section-heading"><p class="eyebrow">Praktisch</p><h2>Alle details op één plek</h2><div class="small-line"></div></div><div class="practical-content"><div class="practical-item"><h3>📍 Locatie</h3><p><strong>Hottentot Hoeve</strong><br/>Cassenbroek 1<br/>2820 Bonheiden</p><a class="button button-secondary" href="https://www.google.com/maps/search/?api=1&query=Hottentot+Hoeve+Bonheiden" target="_blank" rel="noopener noreferrer">Bekijk locatie</a></div><div class="practical-item"><h3>📅 Kalender</h3><p>Zet onze trouwdag alvast in je agenda zodat je hem zeker vrijhoudt.</p><div class="calendar-buttons"><button id="calendarButton2" class="calendar-icon-button" type="button" aria-label="Download kalenderbestand" title="Download kalenderbestand">📅</button><button id="googleCalendarButton" class="calendar-icon-button" type="button" aria-label="Google Calendar" title="Google Calendar"><span class="calendar-provider-icon google-calendar-icon">G</span></button><button id="outlookCalendarButton" class="calendar-icon-button" type="button" aria-label="Outlook Calendar" title="Outlook Calendar"><span class="calendar-provider-icon outlook-calendar-icon">O</span></button><button id="appleCalendarButton" class="calendar-icon-button" type="button" aria-label="Apple Calendar" title="Apple Calendar"><span class="calendar-provider-icon apple-calendar-icon">A</span></button></div><p class="calendar-help">📅 = kalenderbestand · G = Google · O = Outlook · A = Apple</p></div></div></section>
<section id="rsvp" class="section rsvp-section"><div class="section-heading"><p class="eyebrow">RSVP</p><h2>Laat ons weten of je erbij bent</h2><div class="small-line"></div></div><div class="rsvp-content"><div id="rsvp-app">
<div class="invitation-card" id="invitationCard"><div class="invitation-card-inner"><div class="invitation-card-decoration">♡</div><p class="eyebrow">Onze persoonlijke uitnodiging</p><h3>Voor jullie</h3><p class="invitation-card-intro">Open hieronder je persoonlijke uitnodiging met de code die je van ons kreeg.</p><button type="button" id="openInvitationButton" class="button button-primary">Open mijn uitnodiging</button><div id="invitation-code-panel" class="invitation-code-panel" hidden><div class="invitation-card-divider"><span></span><span>♡</span><span></span></div><p class="invitation-code-label">Persoonlijke uitnodigingscode</p><form id="invitationForm"><div class="rsvp-code-row"><input id="invitationCode" name="invitationCode" type="text" placeholder="MG-XXXXXX" autocomplete="off" maxlength="9" required/><button type="submit" class="button button-primary">Open uitnodiging</button></div><div id="invitationLoading" class="invitation-loading" hidden>Uitnodiging laden…</div></form></div></div></div>
<div id="invitationError" class="rsvp-message rsvp-error" hidden></div>
<div id="rsvp-form-container" hidden><div class="rsvp-invitation-heading"><p class="eyebrow">Welkom</p><h3 id="invitationHeading"></h3><p id="invitationIntro"></p></div><form id="rsvpForm"><div id="guestList"></div><div class="rsvp-email-block" style="margin-top:32px;padding:24px 20px;text-align:left;border-top:1px solid rgba(79,84,48,0.14);background:rgba(250,247,240,0.35);"><label for="rsvpEmail" style="display:block;margin-bottom:8px;color:var(--olive-dark);font-family:var(--serif);font-size:1.25rem;font-weight:600;">E-mailadres</label><p style="margin:0 0 14px;color:#777566;font-size:0.76rem;line-height:1.7;">Laat hier je e-mailadres achter als je na ons feest graag nog enkele foto's wilt ontvangen die we met jullie willen delen. <strong>Dit e-mailadres gaat uitsluitend naar Margo &amp; Glenn en wordt met niemand anders gedeeld.</strong></p><input id="rsvpEmail" name="rsvpEmail" type="email" autocomplete="email" maxlength="254" placeholder="jouw@email.be" style="width:100%;height:48px;padding:0 14px;border:1px solid rgba(79,84,48,0.25);background:var(--white);color:var(--olive-dark);font-family:var(--sans);font-size:0.82rem;outline:none;"/></div><div class="rsvp-submit-area"><button type="submit" class="button button-primary">Bevestig RSVP</button></div></form></div>
<div id="rsvp-success" class="rsvp-message rsvp-success" hidden></div></div></div></section>
<footer class="footer"><div class="footer-divider"><span></span><span class="heart">♡</span><span></span></div><p>Margo &amp; Glenn</p><small>02 · 10 · 2027</small></footer>
</main>`

let currentInvitationCode=null
let currentInvitation=null

async function loadInvitation(code){
  const errorElement=document.querySelector('#invitationError'),invitationCard=document.querySelector('#invitationCard'),formContainer=document.querySelector('#rsvp-form-container'),success=document.querySelector('#rsvp-success'),panel=document.querySelector('#invitation-code-panel'),loading=document.querySelector('#invitationLoading'),submitButton=document.querySelector('#invitationForm button[type="submit"]')
  if(!errorElement||!invitationCard||!formContainer||!success||!panel)return
  errorElement.hidden=true;errorElement.textContent='';success.hidden=true;formContainer.hidden=true
  panel.hidden=false;panel.classList.add('is-open');invitationCard.hidden=false
  if(loading){loading.hidden=false;loading.textContent='Uitnodiging laden…'}
  if(submitButton){submitButton.disabled=true;submitButton.textContent='Laden…'}
  const controller=new AbortController();const timeoutId=setTimeout(()=>controller.abort(),10000)
  try{
    const response=await fetch(`/api/invitation?code=${encodeURIComponent(code)}`,{cache:'no-store',headers:{Accept:'application/json'},signal:controller.signal})
    const text=await response.text();let data
    try{data=JSON.parse(text)}catch{throw new Error(response.ok?'De uitnodiging kon niet worden gelezen.':'De uitnodiging kon niet worden geladen. Controleer de code en probeer opnieuw.')}
    if(!response.ok||!data.ok)throw new Error(data.error||'Deze uitnodigingscode is ongeldig.')
    if(!Array.isArray(data.guests)||data.guests.length===0)throw new Error('Deze uitnodiging bevat nog geen gasten. Neem contact op met Margo & Glenn.')
    currentInvitationCode=code;currentInvitation=data;renderInvitation(data)
    invitationCard.hidden=true;formContainer.hidden=false
  }catch(error){
    console.error('Invitation loading failed:',error)
    invitationCard.hidden=false;formContainer.hidden=true
    errorElement.textContent=error.name==='AbortError'?'De uitnodiging laden duurt te lang. Controleer je internetverbinding en probeer opnieuw.':(error.message||'Deze uitnodigingscode kon niet worden geladen.')
    errorElement.hidden=false
  }finally{
    clearTimeout(timeoutId)
    if(loading)loading.hidden=true
    if(submitButton){submitButton.disabled=false;submitButton.textContent='Open uitnodiging'}
  }
}

function renderInvitation(data){const heading=document.querySelector('#invitationHeading'),intro=document.querySelector('#invitationIntro'),guestList=document.querySelector('#guestList'),emailInput=document.querySelector('#rsvpEmail');if(!heading||!intro||!guestList)return;const guests=Array.isArray(data.guests)?data.guests:[],singleGuest=guests.length===1;heading.textContent=singleGuest?`Welkom ${guests[0].name}`:'Welkom';intro.textContent=singleGuest?'Laat me weten voor welke onderdelen je aanwezig zult zijn.':'Laat ons weten voor welke onderdelen jullie aanwezig zullen zijn.';if(emailInput)emailInput.value=data.email||'';guestList.innerHTML=guests.map(renderGuest).join('');setupDietaryControls(guestList)}

function renderGuest(guest){const dinnerStatus=guest.dinnerRsvpStatus||'',eveningStatus=guest.eveningRsvpStatus||'',requirements=Array.isArray(guest.dietaryRequirements)?guest.dietaryRequirements:[],attending=dinnerStatus==='attending'||eveningStatus==='attending';return `<article class="rsvp-guest" data-guest-id="${guest.id}"><div class="rsvp-guest-heading"><h4>${escapeHtml(guest.name)}</h4></div>${guest.invitedToDinner?renderEventChoice('dinner',guest.id,'Diner','Zaterdag 2 oktober 2027',dinnerStatus):''}${guest.invitedToEvening?renderEventChoice('evening',guest.id,'Avondfeest','Zaterdag 2 oktober 2027',eveningStatus):''}${renderDietarySection(guest.id,requirements,attending)}</article>`}
function renderEventChoice(part,id,title,date,status){const attending=status==='attending',declined=status==='declined';return `<div class="rsvp-event"><div class="rsvp-event-heading"><div><h5>${title}</h5><span>${date}</span></div></div><div class="rsvp-choice-group"><label class="rsvp-choice"><input type="radio" name="${part}-${id}" value="attending" ${attending?'checked':''} required/><span>Ja, ik kom</span></label><label class="rsvp-choice"><input type="radio" name="${part}-${id}" value="declined" ${declined?'checked':''} required/><span>Nee, ik kom niet</span></label></div></div>`}
function renderDietarySection(id,requirements,attending){const has=category=>requirements.some(r=>r.category===category),other=requirements.find(r=>r.category==='other'),checked=Boolean(other);return `<div class="rsvp-dietary-wrapper" data-dietary-wrapper="${id}" ${attending?'':'hidden'}><div class="rsvp-dietary"><h6>Allergieën &amp; dieetvoorkeuren</h6><p>Heb je een allergie, intolerantie of dieetvoorkeur? Duid hieronder aan wat voor jou van toepassing is. <strong>We zullen hier in de mate van het mogelijke rekening mee houden.</strong></p><div class="dietary-options">${renderDietaryCheckbox(id,'vegetarian','Vegetarisch',has('vegetarian'))}${renderDietaryCheckbox(id,'vegan','Vegan',has('vegan'))}${renderDietaryCheckbox(id,'other','Andere',checked)}</div><div class="dietary-other" data-dietary-other="${id}" ${checked?'':'hidden'}><input type="text" class="dietary-other-text" data-dietary-other-text="${id}" value="${escapeHtml(other?.otherText||'')}" maxlength="250" placeholder="Gluten allergie" ${checked?'required':''}/></div></div></div>`}
function renderDietaryCheckbox(id,category,label,checked){return `<label class="dietary-option"><input type="checkbox" data-dietary-category="${category}" data-guest-id="${id}" ${checked?'checked':''}/><span>${label}</span></label>`}
function setupDietaryControls(container){container.addEventListener('change',event=>{const target=event.target;if(target.matches('input[type="radio"][name^="dinner-"],input[type="radio"][name^="evening-"]')){const guest=target.closest('.rsvp-guest');if(!guest)return;const attending=Array.from(guest.querySelectorAll('input[type="radio"][name^="dinner-"],input[type="radio"][name^="evening-"]')).some(input=>input.checked&&input.value==='attending');const wrapper=guest.querySelector('[data-dietary-wrapper]');if(wrapper)wrapper.hidden=!attending;return}if(target.matches('input[data-dietary-category]')&&target.dataset.dietaryCategory==='other'){const id=target.dataset.guestId,other=container.querySelector(`[data-dietary-other="${id}"]`),text=container.querySelector(`[data-dietary-other-text="${id}"]`);if(!other)return;other.hidden=!target.checked;if(text){text.required=target.checked;if(!target.checked)text.value=''}}})}

async function submitRsvp(event){event.preventDefault();const form=event.currentTarget,button=form.querySelector('button[type="submit"]'),original=button?button.textContent:'';if(button){button.disabled=true;button.textContent='Bezig...'}try{const guests=collectRsvpGuests(form),emailInput=form.querySelector('#rsvpEmail'),email=emailInput?emailInput.value.trim():'';const response=await fetch('/api/rsvp',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code:currentInvitationCode,email,guests})}),data=await response.json();if(!response.ok||!data.ok)throw new Error(data.error||'Er ging iets mis bij het opslaan van je RSVP.');document.querySelector('#rsvp-form-container').hidden=true;const success=document.querySelector('#rsvp-success');success.innerHTML='<div class="rsvp-success-inner"><div class="rsvp-success-decoration">♡</div><p class="eyebrow">Bedankt!</p><h3>Jullie RSVP is ontvangen.</h3><p>We hebben jullie antwoord goed ontvangen. We kijken ernaar uit om samen met jullie onze dag te vieren.</p></div>';success.hidden=false}catch(error){console.error('RSVP submission failed:',error);let errorElement=form.querySelector('.rsvp-submit-error');if(!errorElement){errorElement=document.createElement('div');errorElement.className='rsvp-message rsvp-error rsvp-submit-error';form.querySelector('.rsvp-submit-area')?.before(errorElement)}errorElement.textContent=error.message||'Er ging iets mis bij het verzenden van je RSVP.';errorElement.hidden=false}finally{if(button){button.disabled=false;button.textContent=original}}}
function collectRsvpGuests(form){return Array.from(form.querySelectorAll('.rsvp-guest')).map(element=>{const id=Number(element.dataset.guestId),guest={id};const dinner=element.querySelector(`input[name="dinner-${id}"]:checked`),evening=element.querySelector(`input[name="evening-${id}"]:checked`);if(dinner)guest.dinner={status:dinner.value};if(evening)guest.evening={status:evening.value};guest.dietaryRequirements=collectDietaryRequirements(element,id);return guest})}
function collectDietaryRequirements(element,id){const section=element.querySelector('.rsvp-dietary');if(!section)return[];const requirements=[];section.querySelectorAll('input[data-dietary-category]').forEach(box=>{if(!box.checked)return;const category=box.dataset.dietaryCategory;if(category!=='other'){requirements.push({category});return}const text=section.querySelector(`[data-dietary-other-text="${id}"]`);requirements.push({category:'other',otherText:text?text.value.trim():''})});return requirements}
function escapeHtml(value){return String(value??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\"/g,'&quot;').replace(/'/g,'&#039;')}

const openInvitationButton=document.querySelector('#openInvitationButton'),invitationPanel=document.querySelector('#invitation-code-panel'),invitationInput=document.querySelector('#invitationCode'),invitationForm=document.querySelector('#invitationForm')
openInvitationButton?.addEventListener('click',()=>{if(!invitationPanel)return;invitationPanel.hidden=false;invitationPanel.classList.add('is-open');openInvitationButton.style.display='none';invitationInput?.focus();invitationInput?.select()})
invitationForm?.addEventListener('submit',async event=>{event.preventDefault();if(!invitationInput)return;const code=invitationInput.value.trim().toUpperCase();if(!code){invitationInput.focus();return}await loadInvitation(code)})
document.querySelector('#rsvpForm')?.addEventListener('submit',submitRsvp)
document.querySelector('#calendarButton')?.addEventListener('click',createCalendarFile)
document.querySelector('#calendarButton2')?.addEventListener('click',createCalendarFile)
document.querySelector('#googleCalendarButton')?.addEventListener('click',openGoogleCalendar)
document.querySelector('#outlookCalendarButton')?.addEventListener('click',openOutlookCalendar)
document.querySelector('#appleCalendarButton')?.addEventListener('click',createCalendarFile)
function updateCountdown(){const countdown=document.querySelector('#countdown');if(countdown)countdown.textContent=formatCountdown()}
updateCountdown();setInterval(updateCountdown,60000)
