import './style.css'
import { guestPortalMarkup, initializeGuestPortal } from './guest-portal.js'

const weddingDate = new Date('2027-10-02T00:00:00')
const calendarEvent = { title:'Margo & Glenn — Onze trouwdag', location:'Hottentot Hoeve, Cassenbroek 1, 2820 Bonheiden', description:'Trouwdag van Margo & Glenn.', startDate:'20271002', endDate:'20271003', startDateTime:'2027-10-02T00:00:00', endDateTime:'2027-10-03T00:00:00' }

function createCalendarFile(){const event=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Margo & Glenn//Wedding//NL','CALSCALE:GREGORIAN','METHOD:PUBLISH','BEGIN:VEVENT','UID:margo-glenn-2027-10-02@wedding',`DTSTAMP:${formatICSDate(new Date())}`,`DTSTART;VALUE=DATE:${calendarEvent.startDate}`,`DTEND;VALUE=DATE:${calendarEvent.endDate}`,`SUMMARY:${escapeICS(calendarEvent.title)}`,`LOCATION:${escapeICS(calendarEvent.location)}`,`DESCRIPTION:${escapeICS(calendarEvent.description)}`,'END:VEVENT','END:VCALENDAR'].join('\r\n');const blob=new Blob([event],{type:'text/calendar;charset=utf-8'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download='Margo-en-Glenn-02-10-2027.ics';document.body.appendChild(link);link.click();link.remove();URL.revokeObjectURL(url)}
function formatICSDate(date){const y=date.getUTCFullYear(),m=String(date.getUTCMonth()+1).padStart(2,'0'),d=String(date.getUTCDate()).padStart(2,'0'),h=String(date.getUTCHours()).padStart(2,'0'),mi=String(date.getUTCMinutes()).padStart(2,'0'),s=String(date.getUTCSeconds()).padStart(2,'0');return `${y}${m}${d}T${h}${mi}${s}Z`}
function escapeICS(value){return String(value).replace(/\\/g,'\\\\').replace(/\r?\n/g,'\\n').replace(/;/g,'\\;').replace(/,/g,'\\,')}
function formatCountdown(){const difference=weddingDate-new Date();if(difference<=0)return 'Vandaag is onze dag ♡';const days=Math.floor(difference/86400000),hours=Math.floor(difference/3600000%24),minutes=Math.floor(difference/60000%60);return `${days} dagen · ${hours} uur · ${minutes} minuten`}
function openGoogleCalendar(){const url='https://calendar.google.com/calendar/render'+'?action=TEMPLATE'+`&text=${encodeURIComponent(calendarEvent.title)}`+`&dates=${calendarEvent.startDate}/${calendarEvent.endDate}`+`&location=${encodeURIComponent(calendarEvent.location)}`+`&details=${encodeURIComponent(calendarEvent.description)}`;window.open(url,'_blank')}
function openOutlookCalendar(){const url='https://outlook.live.com/calendar/0/deeplink/compose'+`?subject=${encodeURIComponent(calendarEvent.title)}`+`&startdt=${encodeURIComponent(calendarEvent.startDateTime)}`+`&enddt=${encodeURIComponent(calendarEvent.endDateTime)}`+`&location=${encodeURIComponent(calendarEvent.location)}`+`&body=${encodeURIComponent(calendarEvent.description)}`;window.open(url,'_blank')}

document.querySelector('#app').innerHTML=`
<main class="site">
<section class="hero"><div class="hero-decoration hero-decoration-left"></div><div class="hero-decoration hero-decoration-right"></div><div class="hero-content"><img class="wedding-logo" src="/logo.png" alt="Margo & Glenn — 2 oktober 2027"/><div class="hero-divider"><span></span><span class="heart">♡</span><span></span></div><p class="eyebrow">Onze trouwdag</p><h1>Laat ons weten<br/><em>of je er kan bij zijn</em></h1><p class="intro">Op 2 oktober 2027 willen we samen met jullie onze liefde vieren en het begin van een nieuw hoofdstuk in ons leven als man en vrouw.</p><div class="hero-actions"><a href="#rsvp" class="button button-primary">RSVP</a><button id="calendarButton" class="button button-secondary" type="button">Voeg toe aan kalender</button></div></div></section>
<section id="details" class="section details-section"><div class="section-heading"><p class="eyebrow">02 · 10 · 2027</p><h2>Onze dag</h2><div class="small-line"></div><div class="adults-only"><strong>Adults only</strong><p>Een avond zonder zorgen voor iedereen.<br/>Daarom vieren we onze dag graag samen zonder kinderen.</p></div></div><div class="details-grid"><article class="detail-card"><div class="detail-icon">♡</div><h3>Wanneer</h3><p>Zaterdag<br/><strong>2 oktober 2027</strong></p></article><article class="detail-card"><div class="detail-icon">⌖</div><h3>Waar</h3><p><strong>Hottentot Hoeve</strong><br/>Cassenbroek 1<br/>2820 Bonheiden</p><a class="text-link" href="https://www.google.com/maps/search/?api=1&query=Hottentot+Hoeve+Bonheiden" target="_blank" rel="noopener noreferrer">Bekijk de locatie →</a></article></div></section>
<section class="countdown-section"><div class="countdown-inner"><p class="eyebrow">En tot dan...</p><h2>We tellen samen af</h2><div id="countdown" class="countdown">${formatCountdown()}</div><div class="hero-divider"><span></span><span class="heart">♡</span><span></span></div></div></section>
<section class="section practical-section"><div class="section-heading"><p class="eyebrow">Praktisch</p><h2>Alle details op één plek</h2><div class="small-line"></div></div><div class="practical-content"><div class="practical-item"><h3>📍 Locatie</h3><p><strong>Hottentot Hoeve</strong><br/>Cassenbroek 1<br/>2820 Bonheiden</p><a class="button button-secondary" href="https://www.google.com/maps/search/?api=1&query=Hottentot+Hoeve+Bonheiden" target="_blank" rel="noopener noreferrer">Bekijk locatie</a></div><div class="practical-item"><h3>📅 Kalender</h3><p>Zet onze trouwdag alvast in je agenda zodat je hem zeker vrijhoudt.</p><div class="calendar-buttons"><button id="calendarButton2" class="calendar-icon-button" type="button" aria-label="Download kalenderbestand" title="Download kalenderbestand">📅</button><button id="googleCalendarButton" class="calendar-icon-button" type="button" aria-label="Google Calendar" title="Google Calendar"><img class="calendar-provider-icon" src="/icons/google-calendar.svg" width="32" height="32" alt="" aria-hidden="true"/></button><button id="outlookCalendarButton" class="calendar-icon-button" type="button" aria-label="Outlook Calendar" title="Outlook Calendar"><img class="calendar-provider-icon" src="/icons/outlook.svg" width="32" height="32" alt="" aria-hidden="true"/></button><button id="appleCalendarButton" class="calendar-icon-button" type="button" aria-label="Apple Calendar" title="Apple Calendar"><img class="calendar-provider-icon" src="/icons/apple-calendar.svg" width="32" height="32" alt="" aria-hidden="true"/></button></div><p class="calendar-help">Kies je agenda of download het kalenderbestand.</p></div></div></section>
${guestPortalMarkup}
<footer class="footer"><div class="footer-divider"><span></span><span class="heart">♡</span><span></span></div><p>Margo &amp; Glenn</p><small>02 · 10 · 2027</small></footer>
</main>`

initializeGuestPortal()
document.querySelector('#calendarButton')?.addEventListener('click',createCalendarFile)
document.querySelector('#calendarButton2')?.addEventListener('click',createCalendarFile)
document.querySelector('#googleCalendarButton')?.addEventListener('click',openGoogleCalendar)
document.querySelector('#outlookCalendarButton')?.addEventListener('click',openOutlookCalendar)
document.querySelector('#appleCalendarButton')?.addEventListener('click',createCalendarFile)
function updateCountdown(){const countdown=document.querySelector('#countdown');if(countdown)countdown.textContent=formatCountdown()}
updateCountdown();setInterval(updateCountdown,60000)
